{"uuid": "1b319cb3-84a4-4573-a433-442716e1e8b5", "children": ["a85cba7a-f7f3-4633-ba85-788599ebdfa7"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "KeyError: 'token'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Testframe/TestCase/test_profile.py\", line 19, in getdata\n    self.request = Send_Request.Request()\n  File \"/Users/test/work/API_Testframe/Common/Send_Request.py\", line 35, in __init__\n    self.get_session = self.session.get_session()\n  File \"/Users/test/work/API_Testframe/Common/Session.py\", line 42, in get_session\n    auth = \"JWT \" + response.json()[\"token\"]\n"}, "start": 1605685741223, "stop": 1605685742633}], "start": 1605685741223, "stop": 1605685742644}