{"uuid": "dfcbdf33-4c01-4ffb-a50f-478f099b28e3", "children": ["43830c5a-49fa-41c9-8921-7205dbb549e2"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "KeyError: 'token'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Testframe/TestCase/test_login.py\", line 28, in getdata\n    self.request = Send_Request.Request()\n  File \"/Users/test/work/API_Testframe/Common/Send_Request.py\", line 32, in __init__\n    auth = \"JWT \" + response.json()[\"token\"]\n"}, "start": 1605685669976, "stop": 1605685672183}], "start": 1605685669976, "stop": 1605685672381}