{"name": "test_login_01", "status": "broken", "statusDetails": {"message": "KeyError: 'token'", "trace": "self = <test_login.TestLogin object at 0x11219f278>\n\n    @pytest.fixture()\n    def getdata(self):\n        print('before')\n    \n        conf = Config()\n        self.data = Datas()\n>       self.request = Send_Request.Request()\n\nTestCase/test_login.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <Common.Send_Request.Request object at 0x1121a2668>\n\n    def __init__(self):\n        \"\"\"\n        :param env:\n        \"\"\"\n        conf = Config()\n        data = Datas()\n        host = conf.host_qiye6\n        url = conf.tokenHost_qiye6\n        data = eval(conf.loginInfo_qiye6)\n        self.headers = eval(conf.headers)\n        response = requests.post(url=url, data=data)\n>       auth = \"JWT \" + response.json()[\"token\"]\nE       KeyError: 'token'\n\nCommon/Send_Request.py:32: KeyError"}, "description": "\n            用例描述：login接口\n        ", "attachments": [{"name": "log", "source": "c57fe4bf-0a29-477c-af74-eb5ba5679779-attachment.txt", "type": "text/plain"}], "start": 1605685669975, "stop": 1605685669975, "uuid": "43830c5a-49fa-41c9-8921-7205dbb549e2", "historyId": "ad46b58c6f38a9e8de6b92b522c7cbff", "testCaseId": "49d28fbbfb79bd9a490d1da4fd8fe957", "fullName": "TestCase.test_login.TestLogin#test_login_01", "labels": [{"name": "story", "value": "测试登录成功"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Login"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Lettos-iMac.local"}, {"name": "thread", "value": "10454-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}