{"uuid": "e53f9751-87de-4932-88db-9e24ffc20de7", "children": ["8d3bfab6-226f-47fc-8adb-8316568ca6b6"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "KeyError: 'token'\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Testframe/TestCase/test_profile.py\", line 19, in getdata\n    self.request = Send_Request.Request()\n  File \"/Users/test/work/API_Testframe/Common/Send_Request.py\", line 32, in __init__\n    auth = \"JWT \" + response.json()[\"token\"]\n"}, "start": 1605685672383, "stop": 1605685672538}], "start": 1605685672383, "stop": 1605685672548}